apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  #labels related to deployment resources
  labels:
    project: roboshop
    tier: frontend
    componenet: frontend
    purpose: deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      project: roboshop
      tier: frontend
      componenet: frontend
      purpose: deployment
# Pod definitions
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        componenet: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
